[package]
name = "sulfur"
version = "0.1.0"
authors = ["Rheydskey <matgag02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.8"
tokio = { version = "0.2", features = ["full"] }
async-std = "1.6.5"

serde =  "1.0.117"
toml = "0.5"

users = "0.11"

structopt = "0.3.20"
indicatif = "0.15.0"